# Generated by Django 5.2.1 on 2025-05-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('body', models.TextField()),
                ('photo', models.ImageField(upload_to='photo')),
                ('created_date', models.DateField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
